name: Mi Laboratorio con Dominio Fijo (La Versión Final)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae tus archivos
      - name: Descargar mis archivos
        uses: actions/checkout@v4

      # 2. Prepara el servidor SSH
      - name: Configurar Servidor SSH
        run: |
          echo "runner:runner" | sudo chpasswd
          sudo usermod -aG sudo runner
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh start

      # --- LA SOLUCIÓN DEFINITIVA: INSTALACIÓN MANUAL Y CONFIGURACIÓN CORRECTA ---
      - name: Instalar No-IP DUC (Modo No Interactivo)
        run: |
          cd /home/runner
          wget https://www.noip.com/client/linux/noip-duc-linux.tar.gz
          tar xf noip-duc-linux.tar.gz
          cd noip-2.1.9-1/
          
          sudo apt-get update && sudo apt-get install -y make gcc
          make
          sudo cp noip2 /usr/local/bin/noip2
          
          # --- ¡AQUÍ ESTÁ EL CAMBIO CRUCIAL! Usamos los nombres correctos. ---
          sudo bash -c 'cat <<EOF > /usr/local/etc/no-ip2.conf
Username=ricardocraft121@gmail.com
Password=titaBELLA
Hostname=vps-ricardo.ddns.net
EOF'
          
          # Ejecutamos el cliente
          sudo /usr/local/bin/noip2

      # Mantiene la VPS viva
      - name: Mantener viva la conexión
        run: sleep 21000
